### ISSUE TITLE
sagemaker_install() fails, can't find sagemaker package

### ISSUE THREAD

**Issue by jcpsantiago** [tmastny/sagemaker#3]
Great initiative!

I tried `sagemaker_install()` and it fails because `sagemaker` is not available in Conda. Instead I had to install `sagemaker-python-sdk`. Do you have configuration that points `sagemaker_install()` to another source (e.g. PyPi)?

**Comment by tmastny** [comment]
Using `...` in `sagemaker_install`, you can send any additional configuration options to [`reticulate::py_install`](https://rstudio.github.io/reticulate/reference/py_install.html). 

You can use the `method` argument of `py_install` to change the installation method. By default it uses `"auto"`, which is why it was pointing to Conda for you. 

However, I think what you bring up is a real bug. I didn't realize that the Sagemaker package was called [`sagemaker-python-sdk`](https://anaconda.org/conda-forge/sagemaker-python-sdk) for Conda and just [`sagemaker`](https://pypi.org/project/sagemaker/#installing-the-sagemaker-python-sdk) for PyPi.

My current implementation naively hardcodes in `sagemaker` for either installation method:
https://github.com/tmastny/sagemaker/blob/4d835ef3f3fbfa64a2ac5dd616eeb491ed3a3f39/R/install.R#L15-L17

The easiest fix will be to have two separate functions, `sagemaker_install_pypi` and `sagemaker_install_conda`. Otherwise with `method = "auto"`, I'd have to figure out a way to determine if their default installation is Conda or PyPi, so I can use the right package name to install.

**Comment by tmastny** [comment]
Or maybe the event simpler way is just to force users to install the Conda version 🤔.

**Comment by jcpsantiago** [comment]
at least for me `reticulate` offered to install miniconda, that's why I have it. Maybe it's its default?
